apiVersion: v1
kind: Service
metadata:
  name: proxy-cluster-ip-service
  namespace: watchtower
spec:
  type: ClusterIP
  selector:
    component: proxy
  ports:
    - port: 8000
      targetPort: 8000
